Feature: Add a tpm to test harness and show PCR7 values
puzzleos/stubby pull request #25
Opened 2022-09-27 14:04 UTC by smoser

Several changes, all around being able to see PCR7 values in the guest.

2022-09-27 14:13 UTC, smoser commented
we see this in the logs now:

```
$ tail -n 9 test-results/efi-shell/sb-shim-allowed/serial.log
==== MINI INITRAMFS INIT ====
[    4.559375] fbcon: Taking over console
[    4.576928] Console: switching to colour frame buffer device 100x37
/INIT COMMAND LINE: /init
/INIT ENVIRON: HOME=/ TERM=linux 
KERNEL COMMAND LINE: root=atomix console=ttyS0
PCR7: 89D502D880A384D838E2FAF2B8E2916EE3F538937B6F414C9D5B7341A56072D4
[    4.774666] sysrq: Power Off
[    4.785032] reboot: Power down
```

2022-09-27 22:02 UTC, hallyn requested changes
Kidding about 2030, but not the os.kill

2022-09-27 22:02 UTC, hallyn commented on test/harness
> +                        os.kill(signal.SIGKILL)
I'm confused - don't you need to provide a pid to kill here?

2022-10-07 01:05 UTC, hallyn approved these changes

2023-07-26 21:21 UTC, merged